version: '3.9'
services:
  webtickets:
    image: ticket-prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: tickets-web-app-prod-c
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
