version: '3.9'
services:
  webtickets:
    image: ticket-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: tickets-web-app-dev-c
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
